### ISSUE TITLE
Pasting a Signal Node using schematics copies the node, then crashes the game.

### ISSUE THREAD

**Issue by Yusuto** [Goobrr/Esoterum#87]
**Platform**: Manjaro Linux x86_64 

**Mindustry Version**: pre-alpha build 135

**Mod Version**: v2.11-119

**Issue**: Mindustry crashes with a `NullPointerException` after copying a Signal Node added by the Esoterum mod. 

**Steps to reproduce**: Copy a Signal Node. Then paste it either directly or save it first and paste it afterwards. The Node may or may not be connect to another Signal Node.

**Save files**: Tested on multiple saves, thus deemed irrelevant.

**`last_log.txt` and/or crash logs**:
```
    ~  java -jar ~/Desktop/mindustry/Mindustry.jar                                                                                                         ✔ 
[I] [Core] Initialized SDL v2.0.10
[I] [Audio] Initialized SoLoud 202111 using MiniAudio at 44100hz / 1323 samples / 2 channels
[I] [GL] Version: OpenGL 4.6.0 / Intel / Mesa Intel(R) Xe Graphics (TGL GT2)
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 17.0.3
[I] [RAM] Available: 3.8 GB
[I] Loaded mod 'esoterum' in 55.50673ms
[I] Loaded mod 'exogenesis' in 90.37856ms
[I] Total time to load: 5895ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 23 community servers.
[I] Saved on exit.
[E] java.lang.NullPointerException: Cannot invoke "esoterum.world.blocks.binary.transmission.BinaryNode$BinaryNodeBuild.updateNeighbours()" because the return value of "esoterum.world.blocks.binary.transmission.BinaryNode$BinaryNodeBuild.linkedNode()" is null
        at esoterum.world.blocks.binary.transmission.BinaryNode.lambda$new$0(BinaryNode.java:36)
        at mindustry.gen.Building.configured(Building.java:1324)
        at mindustry.world.blocks.ConstructBlock.constructFinish(ConstructBlock.java:77)
        at mindustry.gen.Call.constructFinish(Call.java:228)
        at mindustry.world.blocks.ConstructBlock.constructed(ConstructBlock.java:130)
        at mindustry.world.blocks.ConstructBlock$ConstructBuild.construct(ConstructBlock.java:270)
        at mindustry.gen.UnitEntity.update(UnitEntity.java:1560)
        at mindustry.entities.EntityGroup.update(EntityGroup.java:59)
        at mindustry.gen.Groups.update(Groups.java:75)
        at mindustry.core.Logic.update(Logic.java:413)
        at arc.ApplicationCore.update(ApplicationCore.java:37)
        at mindustry.ClientLauncher.update(ClientLauncher.java:177)
        at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

    ~                                                                                                                                            1 ✘  22s  
```

**Comment by Yusuto** [comment]
While trying to find a fix for the bug, I discovered I was just using an outdated version of the mod, and it has already been fixed. Please excuse that mistake, that was my bad. That's why you compile the latest master branch before submitting any bug reports.
I was so excited, this would have been my first GitHub contribution...
Oh well, Bug (has already been) fixed!
